global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "appcrons_metrics"
    scrape_interval: 10s

    static_configs:
      # - targets: ["127.0.0.1:8000"]
      - targets: ["keep-active-backend-v2.onrender.com"]
